### PR TITLE
Fix get package node

### LINKED ISSUE #427: GetPackageNode rpc function exceeds transport limit
For Packages with a large amount of target filenodes, like java packages, the GetPackageNode function exceeds the grpc transport limit.

### PR DESCRIPTION
**Pull request by GiasemiSh**
closes #427

### CODE REVIEW

File: lib/java-qmstr/src/main/java/org/qmstr/util/transformations/CompileJavaTransformation.java [hunk 1]
```diff
@@ -50,7 +50,7 @@
         File destinationDir =  outDirs.stream()
             .filter(od -> isActualClassDir(od, classesRelPath))
             .findFirst()
-            .orElseThrow(() -> new TransformationException(String.format("target class %s was not found", classesRelPath.toString())));
+            .orElseThrow(() -> new TransformationException(String.format("target class %s was not found in %s", classesRelPath.toString(), outDirs.stream().map(od -> od.toString()).collect(Collectors.joining(", ")))));
```
Comment (senaingrid) [inline lib/java-qmstr/src/main/java/org/qmstr/util/transformations/CompileJavaTransformation.java]: need help to understand

File: modules/analyzers/test-analyzer/main.go [hunk 2]
```diff
@@ -45,41 +44,39 @@ func (testanalyzer *TestAnalyzer) Configure(configMap map[string]string) error {
...
-			log.Printf("Unknown test. Please check the test name provided in the configuration.")
-			os.Exit(master.ReturnAnalyzerFailed)
-		}
-		testSuite := []testing.InternalTest{
-			{
-				Name: test,
-				F:    testfunction,
-			},
+	for _, pnp := range pkgNodes {
+		pkgNode = pnp
```
Comment (senaingrid) [inline modules/analyzers/test-analyzer/main.go]: need help to understand

File: modules/builders/qmstr-maven-plugin/src/main/java/org/qmstr/QmstrBuildMojo.java [hunk 3]
```diff
@@ -64,14 +64,21 @@ public void execute() throws MojoExecutionException {
...
 
-        try {
-            Set<Datamodel.FileNode> fileNodes = FilenodeUtils.processSourceFiles(Transform.COMPILEJAVA, sources,
-                    sourceDirs, Collections.singleton(outputDirectory));
-            bsc.SendBuildFileNodes(fileNodes);
-        } catch (TransformationException e) {
-            // ("qmstr plugin could not transform source to target " + e.getMessage());
-        } catch (FileNotFoundException fnfe) {
-            //throw new MojoExecutionException("qmstr plugin could not find the source file " + fnfe.getMessage());
+        for (File source : sources) {
```
Comment (senaingrid) [inline modules/builders/qmstr-maven-plugin/src/main/java/org/qmstr/QmstrBuildMojo.java]: need help to understand
