### PR TITLE
Prevent HTML failures with slashes '/' and empty arrays

### LINKED ISSUE #382: Html reporter fails when a slash '/' exists in the generated directories
If a slash exists in the name of a directory, then Hugo or the html reporter thinks that the part after the slash is a subdirectory.

This issue was noticed while building Debian curl, where the version of the package was debian/7.64.0-3

### LINKED ISSUE #385: Html reporter fails when there are no licenses listed in the data.json files
If there's some license list empty or null the HTML reporter build will fail.

This issue was noticed while building Debian curl, where there are no licenses listed in `data.json` files.

Related to #382

### PR DESCRIPTION
**Pull request by senaingrid**
Now the HTML Reporter uses the common function `RemoveSlash` to replace it with an underscore in packages and project names, preventing the creation of subfolders and inconsistencies between file structures and references inside Hugo building phase.

_A suggestion for the future is to update this function to remove any kind of special character across phases, to prevent related bugs._

It was also added a Hugo function to wrap arrays, making sure that Hugo can build properly even if it's an empty array.

<br>

Fix #382, fix #385

### CODE REVIEW

File: lib/go-qmstr/reporting/package_data.go [hunk 1]
```diff
@@ -12,6 +13,9 @@ type PackageData struct {
 	LicenseDeclared string
 	Targets         []*Target
 	Project         string // The project this package is associated with.
+	CleanedProject  string // Project name without slashes
```
Comment (GiasemiSh) [inline lib/go-qmstr/reporting/package_data.go]: Instead of creating new fields, you can directly use the RemoveSlash() while creating the package data.

**Comment by senaingrid** [comment]
Squashed and dropped unused commits + same final changes. Check it again, please.
